query getMenu($id: ID!) {
  menu(id: $id) {
    id
    name
    icon
    uploadedIcon
    slug
    sellerIDs
    isCollection
    styles
    display
    enableSty
    order
    banner
    linkBanner
    isCmsOfferPage
    offerCollectionId
    menu {
      id
      name
      icon
      uploadedIcon
      slug
      sellerIDs
      isCollection
      styles
      display
      enableSty
      order
      slugRoot
      slugRelative
      isCmsOfferPage
      offerCollectionId
      menu {
        id
        name
        icon
        slug
        sellerIDs
        isCollection
        styles
        display
        enableSty
        order
        slugRoot
        slugRelative
        optionalText
        isCmsOfferPage
        offerCollectionId
      }
    }
  }
}
