mutation edit($editMenu: MenuInput!) {
  editMenu(menuInput: $editMenu) {
    id
    name
    icon
    slug
    sellerIDs
    isCollection
    styles
    display
    enableSty
    order
    slugRoot
    slugRelative
    banner
    linkBanner
    uploadedIcon
    isCmsOfferPage
    offerCollectionId
    menu {
      id
      name
      icon
      slug
      sellerIDs
      isCollection
      styles
      display
      enableSty
      order
      slugRoot
      slugRelative
      isCmsOfferPage
      offerCollectionId

      menu {
        id
        name
        icon
        slug
        sellerIDs
        isCollection
        styles
        display
        enableSty
        order
        slugRoot
        slugRelative
        optionalText
        isCmsOfferPage
        offerCollectionId
      }
    }
  }
}
